# Generated by Django 5.2.12 on 2026-03-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Кабинет'),
        ),
    ]
