# Generated by Django 5.2.12 on 2026-03-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0004_alter_group_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ФИО преподавателя'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('group', 'day_of_week', 'time')},
        ),
    ]
