# Generated by Django 5.2.12 on 2026-03-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0005_alter_schedule_options_alter_subject_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
    ]
