# Generated by Django 5.2.12 on 2026-03-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0006_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AddField(
            model_name='group',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
