# Generated by Django 5.2.12 on 2026-03-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0007_alter_group_options_group_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='room2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Кабинет 2'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_2', to='schedule_app.teacher', verbose_name='Преподаватель 2'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота'), ('Вс', 'Воскресенье')], max_length=10, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Кабинет 1'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_1', to='schedule_app.teacher', verbose_name='Преподаватель 1'),
        ),
    ]
