# Generated by Django 5.2.12 on 2026-03-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0008_schedule_room2_schedule_teacher2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Заметка'),
        ),
    ]
